package mcp

import (
	"context"
	"os"
	"reflect"
	"runtime"
	"strings"
	"testing"
	"time"

	sdk "github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/sanketsudake/chrome-cdp-cli/internal/chrome"
	"github.com/sanketsudake/chrome-cdp-cli/internal/chrometest"
	"github.com/sanketsudake/chrome-cdp-cli/internal/target"
)

// TestBoundBrowserBindsEveryMethod is the sibling of TestDispatchCoversBrowser
// in internal/daemon: it fails when a Browser method added by a later RFC is
// only promoted from the embedded interface, and so silently opts out of
// request cancellation.
//
// A promoted method is compiler-generated, and the runtime reports its source
// as <autogenerated> — which is exactly the difference being asserted. Close is
// the one method that MUST stay promoted: it tears down the shared connection,
// which outlives any one request.
func TestBoundBrowserBindsEveryMethod(t *testing.T) {
	t.Parallel()
	wrapper := reflect.TypeOf(boundBrowser{})
	iface := reflect.TypeOf((*chrome.Browser)(nil)).Elem()
	for i := range iface.NumMethod() {
		name := iface.Method(i).Name
		m, ok := wrapper.MethodByName(name)
		if !ok {
			t.Fatalf("boundBrowser does not implement %s", name)
		}
		file, _ := runtime.FuncForPC(m.Func.Pointer()).FileLine(m.Func.Pointer())
		generated := strings.Contains(file, "autogenerated")
		if name == "Close" {
			if !generated {
				t.Errorf("boundBrowser overrides Close; Close tears down the shared connection and must not be bound to one request")
			}
			continue
		}
		if generated {
			t.Errorf("boundBrowser inherits %s from the embedded Browser instead of binding it — "+
				"a request that is cancelled would not stop it. Add the forwarder in bind.go.", name)
		}
	}
}

// blockingBrowser blocks in Wait until its context ends, and reports what it
// saw.
type blockingBrowser struct {
	chrometest.StubBrowser
	entered chan struct{}
	err     chan error
}

func (b *blockingBrowser) Wait(ctx context.Context, _ string, _ chrome.WaitCond) (map[string]any, error) {
	close(b.entered)
	<-ctx.Done()
	b.err <- ctx.Err()
	return nil, ctx.Err()
}

// A cancelled request cancels the context the driver is blocked on, and the
// AfterFunc that does it is stopped afterwards rather than left behind.
func TestBindCancelsInFlightCall(t *testing.T) {
	t.Parallel()
	stub := &blockingBrowser{entered: make(chan struct{}), err: make(chan error, 1)}
	req, cancel := context.WithCancel(context.Background())
	b := Bind(stub, req)

	done := make(chan struct{})
	go func() {
		defer close(done)
		_, _ = b.Wait(context.Background(), "t", chrome.WaitCond{Text: "never"})
	}()
	select {
	case <-stub.entered:
	case <-time.After(testTimeout):
		t.Fatal("the driver was never entered")
	}
	cancel()
	select {
	case err := <-stub.err:
		if err == nil {
			t.Error("the driver's context was not cancelled")
		}
	case <-time.After(testTimeout):
		t.Fatal("cancelling the request did not cancel the driver's context")
	}
	<-done
}

// An already-cancelled request never lets a call start work. The synchronous
// path matters: going through AfterFunc would hand the driver a context that is
// live for a moment, for a request that is already gone.
func TestBindRefusesAnAlreadyCancelledRequest(t *testing.T) {
	t.Parallel()
	req, cancel := context.WithCancel(context.Background())
	cancel()
	probe := &ctxProbe{seen: make(chan error, 1)}
	_, _ = Bind(probe, req).List(context.Background())
	select {
	case err := <-probe.seen:
		if err == nil {
			t.Error("a call under an already-cancelled request saw a live context")
		}
	default:
		t.Fatal("the probe was not called")
	}
}

type ctxProbe struct {
	chrometest.StubBrowser
	seen chan error
}

func (p *ctxProbe) List(ctx context.Context) ([]target.Info, error) {
	p.seen <- ctx.Err()
	return nil, nil
}

// VS-11: screenshot comes back as an image content block, and a capture the
// caller did not ask to keep leaves nothing behind.
func TestScreenshotReturnsAnImageBlock(t *testing.T) {
	t.Parallel()
	png := []byte("\x89PNG\r\n\x1a\nfake")
	var wrote string
	r := &fakeRunner{reply: func(argv []string) ([]byte, int) {
		path := flagValue(argv, "--output")
		if path == "" {
			t.Error("screenshot ran without an --output path")
			return errEnvelope("screenshot", "generic", "no output", nil), 1
		}
		wrote = path
		if err := os.WriteFile(path, png, 0o600); err != nil {
			t.Errorf("write capture: %v", err)
		}
		return okEnvelope("screenshot", map[string]any{"path": path, "bytes": len(png), "format": "png", "mode": "viewport"}), 0
	}}
	sess := connect(t, r, Options{})
	out := callTool(t, sess, prefix+"screenshot", map[string]any{})
	if out.IsError {
		t.Fatalf("screenshot failed: %v", structured(t, out))
	}
	var img *sdk.ImageContent
	for _, c := range out.Content {
		if b, ok := c.(*sdk.ImageContent); ok {
			img = b
		}
	}
	if img == nil {
		t.Fatal("no image content block in the result")
	}
	if string(img.Data) != string(png) {
		t.Errorf("image payload = %q, want the captured bytes", img.Data)
	}
	if img.MIMEType != "image/png" {
		t.Errorf("mime = %q, want image/png", img.MIMEType)
	}
	// The temporary file is not reported (it is gone) and not left behind.
	if got := structured(t, out); got["path"] != nil {
		t.Errorf("a temporary capture path was reported to the client: %v", got["path"])
	}
	if _, err := os.Stat(wrote); err == nil {
		t.Errorf("the temporary capture %s was left on disk", wrote)
	}
}

// With an explicit output path the file is kept and reported, exactly as the
// CLI does.
func TestScreenshotKeepsAnExplicitOutput(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := dir + "/shot.png"
	r := &fakeRunner{reply: func(argv []string) ([]byte, int) {
		p := flagValue(argv, "--output")
		_ = os.WriteFile(p, []byte("png"), 0o600)
		return okEnvelope("screenshot", map[string]any{"path": p, "bytes": 3}), 0
	}}
	sess := connect(t, r, Options{})
	out := callTool(t, sess, prefix+"screenshot", map[string]any{"output": path})
	if out.IsError {
		t.Fatalf("screenshot failed: %v", structured(t, out))
	}
	if got := structured(t, out); got["path"] != path {
		t.Errorf("path = %v, want %q", got["path"], path)
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("the requested output file is missing: %v", err)
	}
}

func flagValue(argv []string, flag string) string {
	for i, a := range argv {
		if a == flag && i+1 < len(argv) {
			return argv[i+1]
		}
	}
	return ""
}
